#!/bin/python

import os
import shutil
import requests
import argparse
import subprocess

SOURCES = {
        'arch': 'https://archlinux.org/packages/',
        'artix': 'https://packages.artixlinux.org/packages/'
}

parser = argparse.ArgumentParser(
    prog='archpkg',
    description='Utility to download packages from Official Arch repository \
            and merge them into one package.'
)

parser.add_argument('packages', nargs='+')
parser.add_argument('-d', '--depth', default=0, type=int, help='Dependency depth')
parser.add_argument('-x', '--xzm', action='store_true', help='Convert resulting package to "xzm" module')
parser.add_argument('-s', '--strip', action='store_true', help="Remove unnecessary files")
parser.add_argument('--src', default='arch', choices=SOURCES.keys(), help="Source of packages")

args = parser.parse_args()

SRC_URL = SOURCES[args.src]

def get_packages(name, depth):
    pkg_req = requests.get(SRC_URL + 'search/json/?name=' + name)

    if pkg_req.ok:
        json = pkg_req.json()
        if json['results']:
            res = json['results'][0]
            repo = res['repo']
            arch = res['arch']
            url = SRC_URL + repo + '/' + arch + '/' + name + '/download'

            l1 = [url]
            if depth > 0:
                for x in res['depends']:
                    l2 = get_packages(x, depth - 1)
                    if l2:
                        l1.extend(l2)
            return l1
    return None

pkg_urls = list()

for pkg in args.packages:
    local_pkg_urls = get_packages(pkg, args.depth)
    if local_pkg_urls:
        pkg_urls.extend(local_pkg_urls)

pkg_urls = set(pkg_urls)

if not len(pkg_urls):
    print("No packages found")
    exit()

build_dir = args.src + '-' + '-'.join(args.packages) + '/'
if not os.path.exists(build_dir):
    os.mkdir(build_dir)

r_dir = build_dir + 'result/'
if os.path.exists(r_dir):
    shutil.rmtree(r_dir)
os.mkdir(r_dir)

for url in pkg_urls:
    pkg_name = url.split('/')[6]
    pkg_path = build_dir + pkg_name
    if not os.path.exists(pkg_path):
        os.mkdir(pkg_path)
    subprocess.run(['wget', '-O' + pkg_path + '.tar.zst', url])
    subprocess.run(['zstd', '-d', pkg_path + '.tar.zst'])
    subprocess.run(['tar', 'xf', pkg_path + '.tar', '-C' + pkg_path])
    subprocess.run(['rsync', '-au', pkg_path + '/', r_dir])
    os.remove(pkg_path + '.tar.zst')
    os.remove(pkg_path + '.tar')

for x in ['.BUILDINFO', '.MTREE', '.PKGINFO', '.INSTALL']:
    if os.path.exists(r_dir + x):
        os.remove(r_dir + x)
if os.path.exists(r_dir + 'usr/lib'):
    os.rename(r_dir + 'usr/lib', r_dir + 'usr/lib64')
if os.path.exists(r_dir + 'lib'):
    os.rename(r_dir + 'lib', r_dir + 'lib64')

if args.strip:
    for x in ['man', 'zsh', 'locale', 'i18n', 'locale', 'licenses', 'fish', 'doc']:
        if os.path.exists(r_dir + 'usr/share/' + x):
            shutil.rmtree(r_dir + 'usr/share/' + x)

if args.xzm:
    subprocess.run(['dir2xzm', r_dir, '-o', './' + args.src + '-' + '-'.join(args.packages) + '.xzm'])
else:
    subprocess.run(['tar', '-C' + r_dir, '-cJf', args.src + '-' + '-'.join(args.packages) + '.tar.xz', '.'])

shutil.rmtree(build_dir)
print('Finished!')
